version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: npm start
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - 3000:3000
        environment:
            - POSTGRES_DB_HOST=db
            - POSTGRES_DB_PORT=5432
            - POSTGRES_DB_USER=user
            - POSTGRES_DB_PASS=password
            - POSTGRES_DB=motorway
            - NODE_ENV=production
        depends_on:
            - db
    db:
        image: motorway-test-backend
        container_name: motorway-test-backend
        build:
            context: .
            target: motorway-test-backend
            dockerfile: Dockerfile.db
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=motorway
        ports:
            - 5432:5432
